# Generated by Django 6.0.3 on 2026-03-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=10, verbose_name='ИД Продукта ')),
                ('code', models.CharField(max_length=14, verbose_name='Штрих- код')),
                ('description', models.CharField(max_length=200, verbose_name='Описание')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('manufacturer', models.CharField(max_length=80, verbose_name='Производитель')),
                ('status', models.CharField(max_length=8, verbose_name='Статус')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
