# Generated by Django 6.0.3 on 2026-04-10 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_customuser_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
